#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def vsphere_creds():
    username: #@ data.values.vsphere.username
    password: #@ data.values.vsphere.password
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vsphere
  name: capv-manager-bootstrap-credentials
  namespace: capv-system
stringData:
  credentials.yaml: #@ yaml.encode(vsphere_creds())
type: Opaque