#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ "{}-cert-manager-helm-values".format(data.values.cluster_name)
  namespace: #@ data.values.namespace
stringData:
  values.yaml: 'installCRDs: true'
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: #@ "{}-cert-manager".format(data.values.cluster_name)
  namespace: #@ data.values.namespace
spec:
  cluster:
    kubeconfigSecretRef:
      name: #@ "{}-kubeconfig".format(data.values.cluster_name)
      key: value
  fetch:
  - helmChart:
      name: cert-manager
      repository:
        url: https://charts.bitnami.com/bitnami
      version: "0.4.5"

  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        paths:
          00-namespace.yaml: |
            ---
            apiVersion: v1
            kind: Namespace
            metadata:
              labels:
                kubernetes.io/metadata.name: cert-manager
              name: cert-manager
  - helmTemplate:
      name: cert-manager
      namespace: cert-manager
      valuesFrom:
      - secretRef:
          name: #@ "{}-cert-manager-helm-values".format(data.values.cluster_name)
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true