#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: #@ "{}-nginx-ingress-controller".format(data.values.cluster_name)
  namespace: #@ data.values.namespace
spec:
  cluster:
    kubeconfigSecretRef:
      name: #@ "{}-kubeconfig".format(data.values.cluster_name)
      key: value
  syncPeriod: 5m
  paused: false
  fetch:
  - helmChart:
      name: nginx-ingress-controller
      repository:
        url: https://charts.bitnami.com/bitnami
      version: "9.1.5"

  template:
  - helmTemplate:
      name: nginx-ingress-controller
      namespace: nginx-ingress-controller

  - ytt:
      ignoreUnknownComments: true
      inline:
        paths:
          00-namespace.yaml: |
            #@ load("@ytt:overlay", "overlay")
            ---
            apiVersion: v1
            kind: Namespace
            metadata:
              labels:
                kubernetes.io/metadata.name: nginx-ingress-controller
              name: nginx-ingress-controller


            #@ servicemonitor = overlay.subset({"kind": "ServiceMonitor"})
            #@ namespace = overlay.subset({"kind": "Namespace"})
            #@ crd = overlay.subset({"kind": "CustomResourceDefinition"})
            #@overlay/match by=overlay.not_op(overlay.or_op(servicemonitor, namespace, crd)),expects="0+"
            ---
            #@overlay/match missing_ok=True
            metadata:
              #@overlay/match missing_ok=True
              namespace: nginx-ingress-controller
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true