apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: cluster-api
  namespace: kapp-controller
spec:
  serviceAccountName: kapp-controller-clusteradmin
  syncPeriod: 5m
  paused: false
  fetch:
  - git:
      url: https://github.com/Jeremy-Boyle/asi-project
      ref: origin/main
      secretRef:
        name: github-token
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        pathsFrom:
        - secretRef:
            #! This is found in asi-project/deploy/clusters/secrets/vsphere/vpshere-cluster-secret.platform-ops.sops.yaml
            name: vsphere-cluster-secrets
      paths:
      - apps/cluster-api/capi/manifests
      - apps/cluster-api/capa/manifests
      - apps/cluster-api/capo/manifests
      - apps/cluster-api/capv/manifests
      - apps/cluster-api/overlay
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true