apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: cluster-api
  namespace: kapp-controller
spec:
  serviceAccountName: kapp-controller-clusteradmin
  fetch:
  - git:
      url: https://github.com/Jeremy-Boyle/asi-project
      ref: origin/master
      secretRef:
        name: github-token
  template:
  - ytt:
      ignoreUnknownComments: true
      paths:
      - apps/cluster-api/capi/manifests
      - apps/cluster-api/capa/manifests
      - apps/cluster-api/capo/manifests
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true