apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: cluster-secrets
  namespace: kapp-controller
spec:
  serviceAccountName: kapp-controller-clusteradmin
  syncPeriod: 5m
  paused: false
  fetch:
  - git:
      url: https://github.com/Jeremy-Boyle/asi-project
      ref: origin/dev
      secretRef:
        name: github-token
  template:
  - sops:
      pgp:
        privateKeysSecretRef:
          name: cluster-pgp-key
      paths:
      - deploy/clusters/secrets/openstack
      - deploy/clusters/secrets/vsphere
      - deploy/clusters/secrets/shared
      - deploy/stack/tools/secrets
  - ytt:
      ignoreUnknownComments: true
      paths:
      - deploy/clusters/secrets/openstack
      - deploy/clusters/secrets/vsphere
      - deploy/clusters/secrets/shared
      - deploy/stack/tools/secrets
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true