apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: cluster-secrets
  namespace: kapp-controller
spec:
  serviceAccountName: kapp-controller-clusteradmin
  fetch:
  - git:
      url: https://github.com/Jeremy-Boyle/asi-project
      ref: origin/master
      secretRef:
        name: github-token
  template:
  - sops:
      pgp:
        privateKeysSecretRef:
          name: cluster-pgp-key
      paths:
      - deploy/cluster/secrets/
  - ytt:
      ignoreUnknownComments: true
      paths:
      - deploy/cluster/secrets/
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true