#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.all
#@overlay/match by=overlay.subset({ "kind": "DaemonSet", "metadata": { "name": "openstack-cloud-controller-manager" } }),expects="1+"
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name"
      - name: openstack-cloud-controller-manager
        volumeMounts:
        #@overlay/match by="name"
        #@overlay/replace
        - name: cloud-config-volume
          mountPath: /etc/config/cloud.conf
          mountPropagation: "HostToContainer"
      volumes:
      #@overlay/match by="name"
      #@overlay/replace
      - name: cloud-config-volume
        hostPath:
          path: /etc/kubernetes/openstack-cloud.conf
          type: File