apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: #@ data.values.namespace
spec:
  selector:
    component: uptime-kuma
  type: ClusterIP
  ports:
  - name: http
    port: 3001
    targetPort: 3001
    protocol: TCP