#@ load("@ytt:data", "data")
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: #@ "{}-vsphere-controllers".format(data.values.cluster_name)
  namespace: #@ data.values.namespace
spec:
  cluster:
    kubeconfigSecretRef:
      name: #@ "{}-kubeconfig".format(data.values.cluster_name)
      key: value
  syncPeriod: 5m
  paused: false
  fetch:
  - git:
      url: https://github.com/Jeremy-Boyle/asi-project
      ref: origin/main
      secretRef:
        name: github-token
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        pathsFrom:
        - secretRef:
            #! This is found in deploy/clusters/secrets/vsphere/vsphere-cluster-secret.platform-ops.sops.yaml
            name: vsphere-cluster-secrets
      paths:
      - asi-project/apps/vsphere-cloud-controller/manifests
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true