#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

---
apiVersion: v1
kind: Secret
metadata:
  name: csi-vsphere-config
  namespace: kube-system
stringData:
  #@yaml/text-templated-strings
  csi-vsphere.conf: |+
    [Global]
    cluster-id = "default/(@= data.values.cluster_name @)"

    [VirtualCenter "(@= data.values.vsphere.server.fqdn @)"]
    user = "(@= data.values.vsphere.username @)"
    password = "(@= data.values.vsphere.password @)"
    datacenters = "(@= data.values.vsphere.server.datastore @)"

    [Network]
    public-network = "(@= data.values.vsphere.network.name @)"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-provider-vsphere-credentials
  namespace: kube-system
stringData:
  username: #@ data.values.vsphere.username
  password: #@ data.values.vsphere.password
type: Opaque