#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

---
apiVersion: v1
data:
  cacert: #@ base64.encode(data.values.openstack.ca)
  clouds.yaml: #@ base64.encode(data.values.openstack.clouds_file)
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: #@ "{}-cloud-config".format(data.values.cluster_name)
  namespace: #@ data.values.namespace