#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.all
#@overlay/match by=overlay.subset({"kind":"OpenStackMachineTemplate"}),expects="0+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/delete-strategy: "orphan"
    kapp.k14s.io/versioned: ""
    kapp.k14s.io/num-versions: "10"

#@overlay/match by=overlay.subset({"kind":"OpenstackCluster"}),expects="0+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/delete-strategy: "orphan"

#@overlay/match by=overlay.subset({"kind":"KubeadmControlPlane"}),expects="0+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/delete-strategy: "orphan"

#@overlay/match by=overlay.subset({"kind":"KubeadmConfigTemplate"}),expects="0+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/delete-strategy: "orphan"
    kapp.k14s.io/versioned: ""
    kapp.k14s.io/num-versions: "10"
#@overlay/match by=overlay.subset({"kind":"Secret"}),expects="0+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/delete-strategy: "orphan"
    kapp.k14s.io/versioned: ""
    kapp.k14s.io/num-versions: "10"