apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: platform-ops-mgt-cluster
  namespace: kapp-controller
spec:
  serviceAccountName: kapp-controller-clusteradmin
  fetch:
  - git:
      url: https://github.com/Jeremy-Boyle/asi-project
      ref: origin/master
      secretRef:
        name: github-token
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        paths:
          00-additonal-values.yaml: |
            #@ data/values
            ---
            cluster_name: platform-ops-mgt
            namespace: platform-ops
            mgt_cluster: true
        pathsFrom:
        - secretRef:
            #! This is found in deploy/clusters/secrets/openstack/openstack-cluster-secret.sops.yaml
            name: openstack-cluster-secrets
      paths:
      - cluster/manifests/aws/
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: platform-ops-mgt-cluster-common-apps
  namespace: kapp-controller
spec:
  serviceAccountName: kapp-controller-clusteradmin
  fetch:
  - git:
      url: https://github.com/Jeremy-Boyle/asi-project
      ref: origin/master
      secretRef:
        name: github-token
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        paths:
          00-values.yaml: |
            #@ data/values
            ---
            cluster_name: platform-ops-mgt
            namespace: platform-ops
      paths:
      - deploy/apps/common
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true