apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tools-cluster
  namespace: kapp-controller
spec:
  serviceAccountName: kapp-controller-clusteradmin
  syncPeriod: 5m
  paused: false
  fetch:
  - git:
      url: https://github.com/Jeremy-Boyle/asi-project
      ref: origin/dev
      secretRef:
        name: github-token
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        pathsFrom:
        - secretRef:
            #! This is found in deploy/clusters/secrets/openstack/openstack-cluster-secret.sops.yaml
            name: openstack-cluster-secrets
        - secretRef:
            #! This is found in deploy/clusters/secrets/openstack/openstack-cluster-secret.sops.yaml
            name: shared-cluster-secrets
        paths:
          00-additional-values.yaml: |
            #@data/values
            ---
            #@overlay/match missing_ok=True
            cluster_name: tools

            #@overlay/match missing_ok=True
            create_ns: "False"

            #@overlay/match missing_ok=True
            mgt_cluster: "False"

            #@overlay/match missing_ok=True
            namespace: openstack

            #@overlay/match missing_ok=True
            control_plane:
              replicas: 1

            #@overlay/match missing_ok=True
            worker_node:
              replicas: 2

            openstack:
              #@overlay/match missing_ok=True
              network:
                #@overlay/match missing_ok=True
                cidr: "10.0.2.0/24"
                #@overlay/match missing_ok=True
                lb_cidr: "10.0.2.100-10.0.2.110"
      paths:
      - cluster/manifests/openstack
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tools-cluster-common-apps
  namespace: kapp-controller
spec:
  serviceAccountName: kapp-controller-clusteradmin
  syncPeriod: 5m
  paused: false
  fetch:
  - git:
      url: https://github.com/Jeremy-Boyle/asi-project
      ref: origin/dev
      secretRef:
        name: github-token
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        paths:
          00-values.yaml: |
            #@data/values
            ---
            cluster_name: tools
            namespace: openstack
      paths:
      - apps/common/openstack
      - apps/common/shared
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tools-cluster-stack
  namespace: kapp-controller
spec:
  serviceAccountName: kapp-controller-clusteradmin
  syncPeriod: 5m
  paused: false
  fetch:
  - git:
      url: https://github.com/Jeremy-Boyle/asi-project
      ref: origin/dev
      secretRef:
        name: github-token
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        paths:
          00-values.yaml: |
            #@data/values
            ---
            cluster_name: tools
            namespace: openstack
      paths:
      - deploy/stack/mgt/tools/manifests
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true