#@ load("@ytt:data", "data")
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: #@ "{}-gitlab".format(data.values.cluster_name)
  namespace: #@ data.values.namespace
spec:
  cluster:
    kubeconfigSecretRef:
      name: gitlab-kubeconfig
      key: value
  syncPeriod: 5m
  paused: false
  fetch:
  - git:
      url: https://github.com/Jeremy-Boyle/asi-project
      ref: origin/dev
      secretRef:
        name: github-token
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        paths:
          00-values.yaml: |
            #@ load("@ytt:overlay", "overlay")
            ---
            apiVersion: v1
            kind: Namespace
            metadata:
              labels:
                kubernetes.io/metadata.name: gitlab-system
              name: gitlab-system
            ---
      paths:
      - apps/gitlab-operator/manifests
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true