#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.cluster_name
  namespace: #@ data.values.namespace
stringData:
  username: #@ data.values.vsphere.username
  password: #@ data.values.vsphere.password