apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simu8s-cluster
  namespace: kapp-controller
spec:
  serviceAccountName: kapp-controller-clusteradmin
  fetch:
  - git:
      url: https://github.com/Jeremy-Boyle/simu8s-deployment
      ref: origin/master
      secretRef:
        name: github-token
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        pathsFrom:
        - secretRef:
            #! This is found in deploy/cluster/manifest/secrets/cluster-secrets.platform-ops.sops.yaml
            name: simul8s-cluster-secrets
      paths:
      - deploy/cluster/manifests
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simu8s-cluster-common-apps
  namespace: kapp-controller
spec:
  serviceAccountName: kapp-controller-clusteradmin
  fetch:
  - git:
      url: https://github.com/Jeremy-Boyle/simu8s-deployment
      ref: origin/master
      secretRef:
        name: github-token
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        paths:
          00-values.yaml: |
            #@data/values
            ---
            cluster_name: simul8s
            namespace: simul8s

      paths:
      - deploy/apps/common
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true