apiVersion: ENC[AES256_GCM,data:Z18=,iv:qhbhRmO0uX1FaZYItsq+Tho1kq8eles90Dr/Xlw3ZoI=,tag:+EMpSdgqEGd6kn6fSS1fug==,type:str]
kind: ENC[AES256_GCM,data:PnVic2zY,iv:NDYwrbTL6uBTjBSe4RPmSDHlARfMtr5l8AdVmH1iQ+Y=,tag:IhQ6Rx7PtRkNMNbRBeROyQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NWElk7aenDcivQWkaz32Sb0SYiqMtSs=,iv:B0wEiAPcUgPREo3NamWoqP7nleXDhMECUzuTziT5Oq4=,tag:IcQEg7pCuz0e3ODZ/SRL3Q==,type:str]
    namespace: ENC[AES256_GCM,data:5XEStyxDceNmNR566Q/I,iv:RsG1GQQ/hGFQHeU7jHObCGu7wougVfJHuyVnQcWrz2A=,tag:NItmTAhaOqtqVqWfm0FkAg==,type:str]
stringData:
    00-vsphere-values.yaml: ENC[AES256_GCM,data:8Gxs5IMqNe6hfrIk6g8XQhwY4p+U4JGu8gWYKjOS0EpUf/aRxFGQ0l8NLsZmHrrY2lXwTR717VXQpRRTUAOK7qIWUSrb/IPVyp+ukRIcArGg7sii6VoFpw+nO3OExCrqtXVJVQyjC9uNE6V47rN1fsz7Kwa3HALkiqt2UeN0vWNrfINqrJlqmFvpl4xygqWYlkLabDi09sc9UwKyvrJs0XQps3PDP1IbDIWvRQ+qj1lNwiDo4YrfBQcfxydplQY9wgZW+CQKrFEi0fx+dlpMBVp6V9oSuOnC8vf8MaY2lKuqvQ7gqeCxUFB64adxX2K0Ng8ttzrlRgqUAN3bvj4FD1TbzsPPBqKhKZvIaRbzpcFYbM8D4ieY1IkHbXe4gawqfqyaOfBypGwMYpJyjbNzN0J5752d6GtnWyKvSk979Ue2ISkNyUN6O7xAqN17ef4qarNJ0BQMKCcBxTJq6xLv9ff8Pj468jH7d4m3GXH5R8gaN2wWuvRYYXTJztRyOFq/CwFFFkX/utI7iuTc2gk8PGMAo5KsKSGpO9aiYkLe6I59ShMwe9wkGE23Ci02o/6Un7g3OcJNQ8LUYmw1M41w1sDRYLuXqx/MLrKZlJzD4hLTZxrP8bB2wANKDaZsI8VIQhBYkfh2dzoXAhGdFa2VWRaXPphJo8D3VJ2GJFSboSFez0AZTmhXgS1JTiXMpAzHQmiawnIb5AJDWWyN6fkOwaqCNGEOgYB/KgXeVf5/1Q16n8NoVLjB25c3+m+nFFntMJkJvsbQS/cFyzv6LHqq2j82d8DcWtYi53OwdAKAwS7FE72xsufdQp36cG+i4/N3soNhCQ0Pb063h7oiVqqEbQqBarUuMz8v+OWcXgAPkMsrDUSMMvgczfda/rWMCjsbUFzXcnpYl6wwj1acwUy9m4w+aJZcTXb4+cVrYEVjciOhlbzp0ajlNzmD7dCVfnGo7f+rYxZsT7Pz3cK1CqpHdZk+p65JwD/p81UHSlVsAUGRZ/0DwP6EIfPNAe6sH/SciS6PGswSGSDkjs4nSZF5cV15x9IOs4WRSnJhs2V7nJbYVIqhhGKT1GnRjXH8ioTmKkPayasrvoB/Tipcj/64Is2gvoCMarQWTSutegJ9NVOHI24PAOcnjqYfjgFevtkqew5lalLiL1oWXPlJ4SxA6E1KcJWpxy2LNKyUot+40QWH+xqxfeEcu5koN9wBoFkMlbOnApL/i64glYTkdCch3tAw7oiehkcnKZD0rtk54tDFWkbE0sF+TQMrwsBszXx9ELcX3qCTyZyrIJHn+dhzkAZ19RmQeebNDWLJeR94tfKQHWJgWC8BMebhbdhPMVSG7Iw1kWZZtwt2KxUNipJoDDBYfifJLujH1bIlHdOVsg==,iv:zkg/mbdKUqlWw6YOtyL7Yd0zCmPjHeah5hiv0jiyqz4=,tag:itw7W/pm18tTMQGcPtUdgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-20T03:22:45Z"
    mac: ENC[AES256_GCM,data:XsuJMdVJrsdOlimK0nnuarlfmU71lTX6m6PE325mmoDNaXmLjpUGEuzwgC0VixtMMw5DIVkDjTCZ4SgBd20QeiIZtYkee8lKClcGnsykC8BGVs9jbdr1GOMlJQt8EO5XmmVDYbpiTmCDVrKn0Uq85vzae01u/ioUQoFEpORJsig=,iv:84GFgeoWJB7x8GNgnZMUJQoR4yUjoFMkp0DrReZIrxs=,tag:1/mErMCmhmDnB30AH/kd+Q==,type:str]
    pgp:
        - created_at: "2021-12-29T20:10:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAysCUNqOXXfJARAAgV+vC5L7cGE0xOSKjREtCHVFZHBKtC25JFc45kWYwfCd
            8vMpQuBcPABVXu4tWm3eZKi0T+Zv65C7ECI8plo9/gFcRuPIr2LFfNNu4puJOgZ8
            K0nPNlJwt9PHuHbzTe3WezkrbLKwaw+wrQ1pPKWRmTsYAQjiu/B6wgKqkVxv7/zD
            l+MujG8WsQUVgKJFYKcfob+VC4FjEkHJhIf1gO6wFV/SNKBxqruqWejyh2Mlr8lA
            m3GVfA9d9vjNqQLQKh1k7MxfvQf39mjL9E4uyz+Ph5phS9x9lEHHJD5mRg+Erv4M
            5fH6EfLq1My73U8st6dJuTe+a6695FC5hX2sUQfWvmRAXtl57XsColAvF8G5WvLA
            n7/M8ggDWoQxyA3jN5PwGLfxtcGseEfXjB/YhU7/jRDTpplm6maq7MnLBF8m2836
            RvF7ZtpNPTvmP1fKkeq0gc6vmzSv4jq4HaBmkSr7L6BkGJbalXsDHhSt1Vn/KVEk
            6HIYsvs2csYbHnqV7dbQl8QTcensV36trbc7YFJkK5OJ+4gM99LB/5WSNIO4Zr+/
            DwWPWOZ4g9Kpn87FTF/3UWLf/Vm/6cKmWo7WiQ/hXmzOQTs83yWsAss3vs8tkzyL
            TeDDImkeqlcIlyCwIhixL5wMu2df+c85pbpNgF++tHrUdoKb74TmKikg8UyjXDfS
            XgGQ66IO4wdOgkhO9CUIpW4tOsf0yAFUe0JYSBJNm+j9AKomiUB1X2mFoB0B05Bt
            DvPPqpZRnHD60WRwcHGh39h0SshxmGjI8OJlU3NlUHmwqQredPnaKzpiURxyLDU=
            =b1W9
            -----END PGP MESSAGE-----
          fp: 6827F0BDB77701A2E8D369810F2AEB25171A5459
    unencrypted_suffix: _unencrypted
    version: 3.7.1
