#@ load("@ytt:data", "data")
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: #@ data.values.cluster_name
  namespace: #@ data.values.namespace
  labels:
    cni: calico-openstack
    bootstrap: controller-openstack
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.244.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: #@ "{}-control-plane".format(data.values.cluster_name)
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: OpenStackCluster
    name: #@ data.values.cluster_name
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: OpenStackCluster
metadata:
  name: #@ data.values.cluster_name
  namespace: #@ data.values.namespace
  labels:
    cluster.x-k8s.io/cluster-name: #@ data.values.cluster_name
spec:
  allowAllInClusterTraffic: true
  disableAPIServerFloatingIP: #@ data.values.openstack.network.disable_public_ip
  cloudName: openstack
  dnsNameservers:
  - 1.1.1.1
  - 1.0.0.1
  externalNetworkId: #@ data.values.openstack.network.id
  identityRef:
    kind: Secret
    name: #@ "{}-cloud-config".format(data.values.cluster_name)
  managedAPIServerLoadBalancer: #@ data.values.openstack.network.api_loadbalancer
  managedSecurityGroups: true
  nodeCidr: #@ data.values.openstack.network.cidr