---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: calico-cni-aws
  namespace: aws
spec:
  clusterSelector:
    matchLabels:
      cni: calico-aws
  resources:
  - kind: ConfigMap
    name: calico-cni-aws
  strategy: ApplyOnce