#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: #@ "{}-control-plane".format(data.values.cluster_name)
  namespace: #@ data.values.namespace
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: aws
      controllerManager:
        extraArgs:
          cloud-provider: aws
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: '{{ ds.meta_data.local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: '{{ ds.meta_data.local_hostname }}'
      imageRepository: k8s.gcr.io
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AWSMachineTemplate
      name: #@ "{}-control-plane".format(data.values.cluster_name)
  replicas: 1
  version: #@ data.values.k8s.version
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: #@ "{}-control-plane".format(data.values.cluster_name)
  namespace: #@ data.values.namespace
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.platform-ops.com
      instanceType: #@ data.values.instance_type.control_plane
      sshKeyName: default