#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

#@ def label_worker():
- kubectl --kubeconfig /etc/kubernetes/kubelet.conf label node {{ local_hostname }} node-role.kubernetes.io/worker= --overwrite=true
#@ end
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: #@ "{}-md".format(data.values.cluster_name)
  namespace: #@ data.values.namespace
spec:
  clusterName: #@ data.values.cluster_name
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: #@ data.values.cluster_name
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: #@ "{}-md".format(data.values.cluster_name)
      clusterName: #@ data.values.cluster_name
      failureDomain: nova
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachineTemplate
        name: #@ "{}-md".format(data.values.cluster_name)
      version: #@ data.values.k8s.version
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: #@ "{}-md".format(data.values.cluster_name)
  namespace: #@ data.values.namespace
spec:
  template:
    spec:
      ami:
        id: #@ data.values.aws.instance.ami_uuid
      rootVolume:
        size: #@data.values.image.size
        encrypted: true
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: #@ data.values.aws.instance.worker_node
      sshKeyName: #@ data.values.aws.ssh_key
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: #@ "{}-md".format(data.values.cluster_name)
  namespace: #@ data.values.namespace
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: aws
          name: '{{ ds.meta_data.local_hostname }}'
      postKubeadmCommands: #@label_worker()
