#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.all
#@overlay/match by=overlay.subset({"kind":"AWSMachineTemplate"}),expects="0+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/delete-strategy: "orphan"
    kapp.k14s.io/versioned: ""
    kapp.k14s.io/num-versions: "10"

#@overlay/match by=overlay.subset({"kind":"AWSCluster"}),expects="0+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/delete-strategy: "orphan"

#@overlay/match by=overlay.subset({"kind":"KubeadmControlPlane"}),expects="0+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/delete-strategy: "orphan"

#@overlay/match by=overlay.subset({"kind":"KubeadmConfigTemplate"}),expects="0+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/delete-strategy: "orphan"
    kapp.k14s.io/versioned: ""
    kapp.k14s.io/num-versions: "10"
#@overlay/match by=overlay.subset({"kind":"Secret"}),expects="0+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/delete-strategy: "orphan"
    kapp.k14s.io/versioned: ""
    kapp.k14s.io/num-versions: "10"
---
#@ if data.values.mgt_cluster:
#@overlay/match by=overlay.subset({"kind":"KubeadmConfigTemplate"}),expects="0+"
---
spec:
  template:
    spec:
      files:
      - content: #@base64.encode(data.values.openstack.kubernetes.cloud_config)
        encoding: base64
        owner: root
        path: /etc/kubernetes/openstack-cloud.conf
        permissions: "0600"
      - content: #@base64.encode(data.values.openstack.ca)
        encoding: base64
        owner: root
        path: /etc/certs/cacert
        permissions: "0600"
#@ end